"use client"

import { useState, useRef, useEffect } from "react"
import { motion, useScroll, useTransform } from "framer-motion"
import { Github, ExternalLink, ChevronLeft, ChevronRight, Sparkles } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

interface ProjectItem {
  title: string
  description: string
  tags: string[]
  github: string
  demo: string | null
  date: string
  level: number
  xp: number
  team?: string
}

const projects: ProjectItem[] = [
  {
    title: "AntiSlotV8",
    description:
      "Craft engaging XSS challenges effortlessly with CTF-XSS-BOT. This template simplifies setting up an environment for Capture The Flag competitions.",
    tags: ["Defensive", "Web", "Security", "Malware Scanner"],
    github: "https://github.com/mzrismuarf/AntiSlotV8",
    demo: null,
    date: "June 2024 - Present",
    level: 42,
    xp: 8500,
  }, 
  {
    title: "WormHole",
    description: "Shortcut to the core. WormHole is your personal portal to any system. It bypasses all those pesky redirects and dives straight into the heart of a network.",
    tags: ["Pentest", "Bruteforce"],
    github: "https://github.com/mzrismuarf/wormhole",
    demo: null,
    date: "Dec 2024 - Present",
    level: 38,
    xp: 7600,
  },
  {
    title: "LISTSLICERDORK ",
    description:
      "listslicerdork is a powerful Bash script designed to streamline the process of filtering large lists of targets generated by dork generators",
    tags: ["Docker", "Containerization", "PHP", "WordPress"],
    github: "https://github.com/mzrismuarf/listslicerdork",
    demo: null,
    date: "Sep 2024 - Present",
    level: 35,
    xp: 7000,
  },
]

export function ProjectsSection() {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [hoveredCard, setHoveredCard] = useState<number | null>(null)
  const [visibleProjects, setVisibleProjects] = useState(1) // Start with 1 for mobile
  const carouselRef = useRef<HTMLDivElement>(null)
  const sliderRef = useRef<HTMLDivElement>(null)
  const { scrollYProgress } = useScroll({
    target: carouselRef,
    offset: ["start end", "end start"],
  })

  const opacity = useTransform(scrollYProgress, [0, 0.2, 0.8, 1], [0, 1, 1, 0])
  const scale = useTransform(scrollYProgress, [0, 0.2, 0.8, 1], [0.9, 1, 1, 0.9])

  // Touch/swipe handling
  const [touchStart, setTouchStart] = useState<number | null>(null)
  const [touchEnd, setTouchEnd] = useState<number | null>(null)

  // Minimum swipe distance (in px)
  const minSwipeDistance = 50

  const onTouchStart = (e: React.TouchEvent) => {
    setTouchEnd(null) // otherwise the swipe is fired even with usual touch events
    setTouchStart(e.targetTouches[0].clientX)
  }

  const onTouchMove = (e: React.TouchEvent) => {
    setTouchEnd(e.targetTouches[0].clientX)
  }

  const onTouchEnd = () => {
    if (!touchStart || !touchEnd) return
    
    const distance = touchStart - touchEnd
    const isLeftSwipe = distance > minSwipeDistance
    const isRightSwipe = distance < -minSwipeDistance

    if (isLeftSwipe && currentIndex < maxIndex) {
      nextSlide()
    }
    if (isRightSwipe && currentIndex > 0) {
      prevSlide()
    }
  }

  // Responsive visible projects calculation
  useEffect(() => {
    const updateVisibleProjects = () => {
      const width = window.innerWidth
      if (width >= 1024) {
        setVisibleProjects(3) // lg: 3 projects
      } else if (width >= 768) {
        setVisibleProjects(2) // md: 2 projects
      } else {
        setVisibleProjects(1) // sm: 1 project
      }
    }

    updateVisibleProjects()
    window.addEventListener('resize', updateVisibleProjects)
    return () => window.removeEventListener('resize', updateVisibleProjects)
  }, [])

  // Reset currentIndex when visibleProjects changes to prevent out-of-bounds
  useEffect(() => {
    const maxIndex = Math.max(0, projects.length - visibleProjects)
    if (currentIndex > maxIndex) {
      setCurrentIndex(maxIndex)
    }
  }, [visibleProjects, currentIndex])

  const maxIndex = Math.max(0, projects.length - visibleProjects)

  const nextSlide = () => {
    setCurrentIndex((prevIndex) => Math.min(prevIndex + 1, maxIndex))
  }

  const prevSlide = () => {
    setCurrentIndex((prevIndex) => Math.max(prevIndex - 1, 0))
  }

  // Auto-scroll carousel
  useEffect(() => {
    const interval = setInterval(() => {
      if (hoveredCard === null) {
        // Only auto-scroll if no card is being hovered
        setCurrentIndex((prevIndex) => {
          if (prevIndex >= maxIndex) {
            return 0
          }
          return prevIndex + 1
        })
      }
    }, 5000)

    return () => clearInterval(interval)
  }, [maxIndex, hoveredCard])

  return (
    <div className="py-20 bg-gradient-to-b from-background to-black" id="projects">
      <motion.div ref={carouselRef} style={{ opacity, scale }} className="container px-4 mx-auto max-w-7xl">
        <div className="mb-12 text-center">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
          >
            <h2 className="text-5xl font-bold tracking-tight neon-text-blue">Featured Projects</h2>
            <p className="mt-4 text-xl text-muted-foreground">Level up your knowledge with my latest creations</p>
          </motion.div>
        </div>

        <div className="relative projects-slider">
          <div 
            className="overflow-hidden touch-pan-y projects-slider-container"
            onTouchStart={onTouchStart}
            onTouchMove={onTouchMove}
            onTouchEnd={onTouchEnd}
          >
            <motion.div
              ref={sliderRef}
              className="flex projects-slider-container"
              initial={{ x: 0 }}
              animate={{ x: `-${currentIndex * (100 / visibleProjects)}%` }}
              transition={{ 
                type: "spring", 
                stiffness: 150,
                damping: 20,
                mass: 0.5,
                duration: 0.4
              }}
            >
              {projects.map((project, index) => (
                <motion.div
                  key={index}
                  className={`flex-shrink-0 px-3 projects-card ${
                    visibleProjects === 1 ? 'w-full' : 
                    visibleProjects === 2 ? 'w-1/2' : 
                    'w-1/3'
                  }`}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ 
                    duration: 0.4,
                    delay: index * 0.05,
                    ease: "easeOut"
                  }}
                  viewport={{ once: true }}
                  whileHover={{ 
                    y: -5,
                    transition: { duration: 0.2, ease: "easeOut" }
                  }}
                  onHoverStart={() => setHoveredCard(index)}
                  onHoverEnd={() => setHoveredCard(null)}
                >
                  <Card className="h-full overflow-hidden game-card transition-all duration-300 ease-out flex flex-col">
                    <CardHeader className="relative pb-2 border-b border-muted flex-shrink-0">
                      <div className="absolute top-2 right-2 px-2 py-1 text-xs rounded-full bg-primary/20 text-primary">
                        LVL {project.level}
                      </div>
                      <CardTitle className="text-xl neon-text">
                        <div className="flex items-center gap-2">
                          {project.title}
                          {hoveredCard === index && (
                            <motion.div
                              animate={{
                                rotate: [0, 10, -10, 0],
                                scale: [1, 1.2, 1],
                              }}
                              transition={{
                                duration: 1.5,
                                repeat: Number.POSITIVE_INFINITY,
                                repeatType: "loop",
                                ease: "easeInOut"
                              }}
                            >
                              <Sparkles className="w-4 h-4 text-yellow-500" />
                            </motion.div>
                          )}
                        </div>
                      </CardTitle>
                      <CardDescription className="line-clamp-3">{project.description}</CardDescription>
                    </CardHeader>
                    <CardContent className="pt-4 flex-grow flex flex-col justify-between">
                      <div className="space-y-4">
                        <div className="mb-4">
                          <div className="flex items-center justify-between mb-1">
                            <span className="text-xs">XP</span>
                            <span className="text-xs">{project.xp} / 10000</span>
                          </div>
                          <div className="xp-bar">
                            <div 
                              className="xp-bar-fill transition-all duration-700 ease-out" 
                              style={{ width: `${(project.xp / 10000) * 100}%` }}
                            ></div>
                          </div>
                        </div>

                        <div className="flex flex-wrap gap-2 mb-4">
                          {project.tags.map((tag) => (
                            <Badge key={tag} variant="secondary" className="bg-primary/20 hover:bg-primary/30 transition-colors duration-200 text-xs">
                              {tag}
                            </Badge>
                          ))}
                        </div>
                      </div>
                      
                      <div className="text-sm text-muted-foreground mt-auto">
                        <p>{project.date}</p>
                        {project.team && <p className="mt-1">Associated with {project.team}</p>}
                      </div>
                    </CardContent>
                    <CardFooter className="flex gap-2 border-t border-muted flex-shrink-0 mt-auto">
                      <Link href={project.github} target="_blank" rel="noopener noreferrer" className="flex-1">
                        <Button
                          variant="outline"
                          size="sm"
                          className="w-full gap-1 border-primary/50 hover:border-primary hover:bg-primary/10 transition-all duration-200"
                        >
                          <Github className="w-4 h-4" />
                          GitHub
                        </Button>
                      </Link>
                      {project.demo && (
                        <Link href={project.demo} target="_blank" rel="noopener noreferrer" className="flex-1">
                          <Button
                            variant="outline"
                            size="sm"
                            className="w-full gap-1 border-secondary/50 hover:border-secondary hover:bg-secondary/10 transition-all duration-200"
                          >
                            <ExternalLink className="w-4 h-4" />
                            Demo
                          </Button>
                        </Link>
                      )}
                    </CardFooter>
                  </Card>
                </motion.div>
              ))}
            </motion.div>
          </div>

          {/* Navigation Buttons - Improved mobile positioning */}
          {currentIndex > 0 && (
            <Button
              variant="ghost"
              size="icon"
              className="absolute left-2 md:left-0 z-10 transform -translate-y-1/2 bg-background/80 top-1/2 hover:bg-background backdrop-blur-sm projects-nav-button transition-all duration-200 ease-out"
              onClick={prevSlide}
              aria-label="Previous project"
            >
              <ChevronLeft className="w-6 h-6" />
            </Button>
          )}

          {currentIndex < maxIndex && (
            <Button
              variant="ghost"
              size="icon"
              className="absolute right-2 md:right-0 z-10 transform -translate-y-1/2 bg-background/80 top-1/2 hover:bg-background backdrop-blur-sm projects-nav-button transition-all duration-200 ease-out"
              onClick={nextSlide}
              aria-label="Next project"
            >
              <ChevronRight className="w-6 h-6" />
            </Button>
          )}
        </div>

        {/* Pagination Dots - Updated calculation */}
        <div className="flex justify-center mt-8 gap-2">
          {Array.from({ length: Math.ceil(projects.length / visibleProjects) }).map((_, index) => (
            <Button
              key={index}
              variant="ghost"
              size="sm"
              className={`w-2 h-2 md:w-3 md:h-3 p-0 rounded-full transition-all duration-300 ease-out projects-pagination-dot ${
                index === Math.floor(currentIndex / visibleProjects) 
                  ? "bg-primary scale-110 shadow-lg shadow-primary/30" 
                  : "bg-muted hover:bg-primary/50 hover:scale-105"
              }`}
              onClick={() => setCurrentIndex(index * visibleProjects)}
              aria-label={`Go to slide ${index + 1}`}
            />
          ))}
        </div>

        {/* Mobile swipe hint */}
        <div className="mt-4 text-center md:hidden">
          <p className="text-sm text-muted-foreground">Swipe left or right to navigate</p>
        </div>

        <div className="mt-12 text-center">
          <Link href="https://github.com/dimasma0305?tab=repositories" target="_blank" rel="noopener noreferrer">
            <Button
              variant="outline"
              className="gap-2 border-2 border-primary/50 hover:border-primary hover:bg-primary/10"
            >
              View All Projects
              <ExternalLink className="w-4 h-4" />
            </Button>
          </Link>
        </div>
      </motion.div>
    </div>
  )
}
