name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Refresh blog content and check for updates
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: "22adb469a81d802b93d4f91cb478fada"
        INDEX_OUTPUT: "public/posts/index.json"
        FULL_INDEX_OUTPUT: "public/blog-index.json"
        POSTS_DIR: "public/posts"
      run: |
        echo "🔄 Refreshing content..."
        npm run refresh-content || echo "⚠️ Content refresh script not found, skipping..."
        echo "✅ Content refresh completed"

    - name: Refresh notes content and check for updates
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        NOTION_DATABASE_ID: "22adb469a81d802b93d4f91cb478fada"
        INDEX_OUTPUT: "public/notes/index.json"
        FULL_INDEX_OUTPUT: "public/notes-index.json"
        POSTS_DIR: "public/notes"
      run: |
        echo "🔄 Refreshing content..."
        npm run refresh-content || echo "⚠️ Content refresh script not found, skipping..."
        echo "✅ Content refresh completed"

    - name: Build with Next.js
      run: npm run build
      env:
        NODE_ENV: production
        NEXT_PUBLIC_BASE_URL: "https://blog.mizar.my.id/portofolio/"
        NEXT_PUBLIC_BASE_PATH: ""

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Post-deployment SEO verification
      run: |
        echo "🎉 Deployment successful!"
        echo "📍 Site URL: ${{ steps.deployment.outputs.page_url }}"
        echo "🗺️ Sitemap: ${{ steps.deployment.outputs.page_url }}sitemap.xml"
        echo "🤖 Robots.txt: ${{ steps.deployment.outputs.page_url }}robots.txt"
        echo ""
        echo "📋 Next steps for SEO:"
        echo "1. Submit sitemap to Google Search Console"
        echo "2. Submit sitemap to Bing Webmaster Tools" 
        echo "3. Test with Google Rich Results Test"
        echo "4. Verify OpenGraph tags with Facebook Debugger" 